# Generated by Django 2.1.8 on 2019-04-03 08:37

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.AutoField(db_column='HfID', primary_key=True, serialize=False)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('code', models.CharField(db_column='HFCode', max_length=8)),
                ('acc_code', models.CharField(blank=True, db_column='AccCode', max_length=25, null=True)),
                ('name', models.CharField(db_column='HFName', max_length=100)),
                ('level', models.CharField(db_column='HFLevel', max_length=1)),
                ('address', models.CharField(blank=True, db_column='HFAddress', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='eMail', max_length=50, null=True)),
                ('care_type', models.CharField(db_column='HFCareType', max_length=1)),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom')),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('offline', models.BooleanField(db_column='OffLine')),
                ('row_id', models.BinaryField(blank=True, db_column='RowID', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblHF',
                'managed': False,
            },
        ),
    ]
