# Generated by Django 3.0.14 on 2021-06-01 11:32

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_healthfacilitycatchment_healthfacilitylegalform_healthfacilitymutation_healthfacilitysublevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerVillage',
            fields=[
                ('id', models.AutoField(db_column='OfficerVillageId', primary_key=True, serialize=False)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom')),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('audit_user_id', models.IntegerField(db_column='AuditUserID')),
            ],
            options={
                'db_table': 'tblOfficerVillages',
                'managed': False,
            },
        ),
    ]
