# Generated by Django 3.0.14 on 2021-11-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0006_users_api"),
    ]

    operations = [
        migrations.RunSQL(
            """
        CREATE NONCLUSTERED INDEX ix_tblLocation_parentLocationId ON [dbo].[tblLocations]
        (
            [ParentLocationId] ASC,
            [LegacyID] ASC
        )""",
            reverse_sql="DROP INDEX ix_tblLocation_parentLocationId ON tblLocations",
        )
    ]
