# Generated by Django 3.2.16 on 2023-03-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0011_auto_20230317_0924"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="healthfacility",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"managed": True},
        ),
    ]
