# Generated by Django 3.2.17 on 2026-02-10 19:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('location', '0019_alter_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='program',
            field=models.ManyToManyField(to='program.Program'),
        )
    ]
